### ISSUE TITLE
Update Gleam.py

### ISSUE THREAD

**Issue by py310** [ton-society/the-open-league#177]
When performing a transaction in @GleamRewardsBot as part of the The Open League quest, the transaction goes to the address EQAy0G_D3ma7BLJifaoNwR08kACx3KUfJaneznVKvWCF0RS8, but this address is not listed in the addresses in the file projects/apps/Gleam.py, and the transaction is not counted in the Leaderboard.

**Comment by aleksandrkaekhtin** [comment]
The address EQAy0G_D3ma7BLJifaoNwR08kACx3KUfJaneznVKvWCF0RS8 has been added
